-- Run this in the Puffs Supabase SQL editor:
-- https://nttdxpsqpyokzqyihmcr.supabase.co
-- The Vercel server synchronizes this catalog using a server-only key.

create table if not exists categories (
  id bigint primary key,
  slug text not null unique,
  name_ar text not null,
  name_en text not null,
  image_url text not null default '',
  sort_order integer not null default 0,
  active boolean not null default true
);

create table if not exists products (
  id bigint primary key,
  slug text not null unique,
  name_ar text not null,
  name_en text not null default '',
  description_ar text not null default '',
  description_en text not null default '',
  category_id bigint,
  price integer not null default 0,
  compare_at integer,
  image_url text not null default '',
  featured boolean not null default false,
  in_stock boolean not null default true,
  sort_order integer not null default 0
);

create table if not exists banners (
  id bigint primary key,
  title text not null default '',
  subtitle text not null default '',
  image_url text not null,
  link_url text not null default '/shop',
  sort_order integer not null default 0,
  active boolean not null default true
);

create table if not exists orders (
  id bigint generated by default as identity primary key,
  customer_name text not null,
  phone text not null,
  address text not null default '',
  notes text not null default '',
  items_json text not null,
  total integer not null default 0,
  status text not null default 'new' check (status in ('new', 'done', 'cancelled')),
  created_at timestamptz not null default now()
);

create index if not exists orders_created_at_idx on orders (created_at desc);

alter table categories enable row level security;
alter table products enable row level security;
alter table banners enable row level security;
alter table orders enable row level security;

drop policy if exists "public read categories" on categories;
drop policy if exists "public read products" on products;
drop policy if exists "public read banners" on banners;
drop policy if exists "write categories" on categories;
drop policy if exists "write products" on products;
drop policy if exists "write banners" on banners;
drop policy if exists "public read orders" on orders;

create policy "public read categories" on categories for select using (true);
create policy "public read products" on products for select using (true);
create policy "public read banners" on banners for select using (true);
